import fs from 'fs';
import path from 'path';
import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';
import type {Options as DocsOptions} from '@docusaurus/plugin-content-docs';
import {PROJECTS} from './src/projects';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: "Beep's Workshop",
  tagline: '', // TODO: your tagline (used in <meta>); homepage copy lives in src/pages/index.tsx
  favicon: undefined, // TODO: add static/img/favicon.ico and set this to 'img/favicon.ico'

  future: {v4: true},

  url: 'https://workshop.beepsterr.com',
  baseUrl: '/',

  organizationName: 'Beeps-Workshop',
  projectName: 'workshop',

  onBrokenLinks: 'throw',

  i18n: {defaultLocale: 'en', locales: ['en']},

  // No default docs instance — each project gets its own versioned instance below.
  presets: [
    [
      'classic',
      {
        docs: false,
        blog: false,
        theme: {customCss: './src/css/custom.css'},
      } satisfies Preset.Options,
    ],
  ],

  // One independently-versioned docs instance per project.
  // Freeze a release with:  npm run docusaurus docs:version:<id> <version>
  plugins: PROJECTS.map((p) => {
    // A project uses its own projects/<id>/sidebars.ts if present, else the generic autogenerated one.
    const ownSidebar = `projects/${p.id}/sidebars.ts`;
    const options: DocsOptions = {
      id: p.id,
      path: `projects/${p.id}/docs`,
      routeBasePath: p.id,
      sidebarPath: fs.existsSync(path.join(__dirname, ownSidebar)) ? `./${ownSidebar}` : './sidebars.ts',
      // Docs live in this repo, so "edit this page" points back here — at the real file, whether it's
      // the current version (projects/<id>/docs/...) or a frozen one (<id>_versioned_docs/version-x/...).
      editUrl: ({versionDocsDirPath, docPath}) =>
        `https://github.com/Beeps-Workshop/docs/edit/main/${versionDocsDirPath}/${docPath}`,
    };
    // Versioned projects: serve the last released version by default and label the
    // editable current docs as unreleased "Snapshots" (see lastVersion in src/projects.ts).
    if (p.lastVersion) {
      options.lastVersion = p.lastVersion;
      options.versions = {current: {label: 'Snapshots', banner: 'unreleased'}};
    }
    return ['@docusaurus/plugin-content-docs', options];
  }),

  themeConfig: {
    colorMode: {respectPrefersColorScheme: true},
    navbar: {
      title: "Beep's Workshop",
      // TODO: add static/img/logo.png and uncomment:
      // logo: {alt: "Beep's Workshop", src: 'img/logo.png'},
      items: [
        // Projects grouped into Mods / Plugins dropdowns (kind lives in src/projects.ts).
        ...(['mod', 'plugin'] as const).map((kind) => ({
          type: 'dropdown' as const,
          label: kind === 'mod' ? 'Mods' : 'Plugins',
          position: 'left' as const,
          items: PROJECTS.filter((p) => p.kind === kind).map((p) => ({
            type: 'docSidebar' as const,
            sidebarId: 'docs',
            docsPluginId: p.id,
            label: p.short,
          })),
        })),
        // One version selector per versioned project. Each is tagged with a class so
        // custom.css can show only the one for the project you're currently viewing.
        ...PROJECTS.filter((p) => p.lastVersion).map((p) => ({
          type: 'docsVersionDropdown' as const,
          docsPluginId: p.id,
          position: 'right' as const,
          className: `navbar-version-dropdown navbar-version-dropdown--${p.id}`,
        })),
        {
          href: 'https://github.com/Beeps-Workshop',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'More',
          items: [
            {label: 'Contact', to: '/contact'},
            {label: 'Privacy Policy', to: '/privacy'},
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Beep's Workshop.`,
    },
    prism: {
      additionalLanguages: ['java', 'yaml'],
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
