import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// One generic sidebar, auto-built from each project's folder. Every docs instance points its
// sidebarPath here, so each project gets a sidebar generated from its own files. Control ordering
// and grouping with `sidebar_position` frontmatter and `_category_.json` files inside each project.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
