import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Curated sidebar for BetterKeepInventory's *current* (Snapshots) version, mirroring the order its
// frozen versions use. Keyed `docs` to match this site's instances (BKI's versioned sidebars were
// migrated from `tutorialSidebar` to `docs`).
const sidebars: SidebarsConfig = {
  docs: [
    'index',
    'Installing',
    'Troubleshooting',
    'Configuration',
    {
      type: 'category',
      label: 'Rules',
      items: [
        'Rules/Intro',
        {type: 'category', label: 'Examples', items: [{type: 'autogenerated', dirName: 'Rules/Examples'}]},
        {type: 'category', label: 'Effects', items: [{type: 'autogenerated', dirName: 'Rules/Effects'}]},
        {type: 'category', label: 'Conditions', items: [{type: 'autogenerated', dirName: 'Rules/Conditions'}]},
      ],
    },
    {type: 'category', label: 'Types', items: [{type: 'autogenerated', dirName: 'Types'}]},
    'API',
    {type: 'category', label: 'Changelogs', items: [{type: 'autogenerated', dirName: 'Changelogs'}]},
  ],
};

export default sidebars;
